# Generated by Django 6.0.2 on 2026-03-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0004_property_broker'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_properties',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='Listings.property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('broker', 'Broker'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
