# Generated by Django 6.0.2 on 2026-02-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Listings', '0007_alter_district_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_price', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('down_payment', models.IntegerField()),
                ('repayment_years', models.IntegerField()),
                ('linked_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests', to='Listings.property')),
            ],
        ),
    ]
