# Generated by Django 6.0.2 on 2026-03-13 18:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Shumen', 'Shumen'), ('Vidin', 'Vidin')], default='Sofia', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='Listings.city')),
            ],
            options={
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('size', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('balconies', models.PositiveIntegerField(default=0)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Garage', 'Garage'), ('Office', 'Office'), ('Land', 'Land'), ('Other', 'Other')], default='Other', max_length=255)),
                ('build_year', models.PositiveIntegerField(default=0)),
                ('build_type', models.CharField(choices=[('Brick', 'Brick'), ('Panel', 'Panel'), ('EPK', 'EPK'), ('Wood', 'Wood'), ('Other', 'Other')], default='Other', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('heating', models.CharField(choices=[('Gas', 'Gas'), ('Electricity', 'Electricity'), ('Parno', 'Parno'), ('Floor', 'Floor'), ('Other', 'Other')], default='Other', max_length=255)),
                ('exposure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], max_length=1), blank=True, default=list)),
                ('floor', models.CharField(default=0, max_length=255)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='Listings.amenity')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='Listings.district')),
            ],
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='uniq_district_name_per_city'),
        ),
    ]
