# Generated by Django 6.0.2 on 2026-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('size', models.PositiveIntegerField(max_length=255, verbose_name='Size')),
                ('bedrooms', models.PositiveIntegerField(max_length=255, verbose_name='Bedrooms')),
                ('rooms', models.PositiveIntegerField(max_length=255, verbose_name='Rooms')),
                ('bathrooms', models.PositiveIntegerField(max_length=255, verbose_name='Bathrooms')),
                ('price', models.PositiveIntegerField(max_length=255, verbose_name='Price')),
            ],
        ),
    ]
