# Generated by Django 6.0.2 on 2026-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='district',
            name='uniq_district_name_per_city',
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(choices=[('Center', 'Center'), ('Mladost', 'Mladost'), ('Drujba', 'Drujba'), ('Lozenets', 'Lozenets'), ('Trakia', 'Trakia'), ('Chayka', 'Chayka'), ('Lazur', 'Lazur'), ('Zdravets', 'Zdravets'), ('Other', 'Other')]),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Shumen', 'Shumen'), ('Vidin', 'Vidin')], default='Sofiq'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
