# Generated by Django 6.0.2 on 2026-02-15 19:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Shumen', 'Shumen'), ('Vidin', 'Vidin')], default='Sofia', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='build_type',
            field=models.CharField(choices=[('Brick', 'Brick'), ('Panel', 'Panel'), ('EPK', 'EPK'), ('Wood', 'Wood'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='build_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='exposure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], max_length=1), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Electricity', 'Electricity'), ('Parno', 'Parno'), ('Floor', 'Floor'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Garage', 'Garage'), ('Office', 'Office'), ('Land', 'Land'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mladost', 'Mladost'), ('Drujba', 'Drujba'), ('Center', 'Center'), ('Vitosha', 'Vitosha'), ('Hipodruma', 'Hipodruma'), ('Nadeja', 'Nadeja'), ('Liulin', 'Liulin'), ('Borovo', 'Borovo'), ('Other', 'Other')], default='Other', max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='Listings.city')),
            ],
            options={
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='Listings.district'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='uniq_district_name_per_city'),
        ),
    ]
