# Generated by Django 6.0.2 on 2026-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_remove_district_uniq_district_name_per_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('Comfort', 'Comfort'), ('Security', 'Security'), ('Outdoor', 'Outdoor'), ('Accessibility', 'Accessibility'), ('Building', 'Building')], default='Comfort', max_length=30),
        ),
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
