# Generated by Django 6.0.2 on 2026-03-21 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0003_amenity_category_amenity_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='broker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'broker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
