# Generated by Django 6.0.2 on 2026-02-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0003_city_property_balconies_property_build_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='Listings.district'),
            preserve_default=False,
        ),
    ]
