# Generated by Django 6.0.2 on 2026-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0004_alter_property_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
