# Generated by Django 6.0.2 on 2026-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtor',
        ),
        migrations.AddField(
            model_name='userinquiry',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinquiry',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinquiry',
            name='request_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('OTHER', 'Other')], default='OTHER'),
        ),
        migrations.AlterField(
            model_name='userinquiry',
            name='message',
            field=models.TextField(),
        ),
    ]
