# Generated by Django 6.0.2 on 2026-03-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_remove_district_uniq_district_name_per_city_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquiry',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='Listings.property'),
            preserve_default=False,
        ),
    ]
