# Generated by Django 6.0.2 on 2026-03-21 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userinquiry_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquiry',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be 6–12 characters and may contain digits, + or /.', regex='^[0-9+/]{6,12}$')]),
        ),
    ]
